name: Mirror

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: git-mirror
        uses: wearerequired/git-mirror-action@v1.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:supes1100/circlici-test.git
          destination-repo: git@github.com:TheTipsyTurtle/circlecitest3.git
